### ISSUE TITLE
error when trying to integrate 

### ISSUE THREAD

**Issue by InushaDeSilva** [pruizlezcano/whatsapp-bot#2]
at msgHandler (C:\Users\DELL\Desktop\Whatsapp-Botto-Re-master\msgHandler.js:334:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

iget this, could there be areason

**Comment by pruizlezcano** [comment]
That file is not in my bot so I don't know how it works and why the error might be generated.
